app:
  title: Scaffolded Backstage App
  baseUrl: ${APP_BASE_URL}

  analytics:
    ga4:
      measurementId: ${GA_MEASUREMENT_ID}
      contentGrouping: pluginId
      allowedContexts: ["pluginId"]
#      testMode: true # Prevents data being sent to GA

organization:
  name: ${ORG_NAME}

backend:
  # auth:
  #   dangerouslyDisableDefaultAuthPolicy: true

  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}

  logger:
    meta:
      env: prod

    level: info

    overrides:
      # Set the log level to 'debug' for the catalog plugin logs
      - matchers:
          plugin: catalog
        level: debug

      # Ignore 'info' incoming HTTP requests logs from the rootHttpRouter service
      - matchers:
          service: rootHttpRouter
          type: incomingRequest
        level: warn

      # Ignore logs starting with "Registered scheduled task", unless they're warnings or errors
      # - matchers:
      #     message: ['/^Registered scheduled task/']
      #   level: warn

  baseUrl: ${APP_BASE_URL}
  listen:
    port: ${APP_PORT}
    host: ${APP_HOST}
  csp:
    connect-src: ["'self'", "http:", "https:"]
    img-src:
      [
        "'self'",
        "data:",
        "https://avatars.githubusercontent.com",
        "https://img.shields.io",
        "https://www.google-analytics.com",
      ]
    script-src:
      [
        "'self'",
        "'unsafe-eval'",
        "https://www.google-analytics.com",
        "https://www.googletagmanager.com",
      ]
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: ${APP_BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is stored in app-config.production.yaml
  database:
    #    client: better-sqlite3
    #    connection: ':memory:'
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    prefix: "backstage_"
    # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir
    # https://node-postgres.com/features/ssl
    # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
    # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
    # ssl:
    #   ca: # if you have a CA file and want to verify it you can uncomment this section
    #     $file: <file-path>/ca/server.crt
    # Refer to Tarn docs for default values on PostgreSQL pool configuration - https://github.com/Vincit/tarn.js
    knexConfig:
      pool:
        min: 3
        max: 12
        acquireTimeoutMillis: 60000
        idleTimeoutMillis: 60000

integrations:
  github:
    - host: github.com
      # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
      # about setting up the GitHub integration here: https://backstage.io/docs/integrations/github/locations#configuration
      # token: ${GITHUB_TOKEN}
      # OR:
      apps:
        - appId: ${GITHUB_APP_ID}
          clientId: ${GITHUB_APP_CLIENT_ID}
          clientSecret: ${GITHUB_APP_CLIENT_SECRET}
          webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
          privateKey: ${GITHUB_APP_PRIVATE_KEY}

proxy:
  endpoints:
    "/sentry/api":
      target: https://sentry.io/api/
      allowedMethods: ["GET"]
      headers:
        Authorization: Bearer ${SENTRY_TOKEN}
    "/newrelic/apm/api":
      target: https://api.eu.newrelic.com/v2/
      headers:
        X-Api-Key: ${NEW_RELIC_REST_API_KEY}
      allowedHeaders:
        - link
    "/newrelic/api":
      target: https://api.eu.newrelic.com/
      headers:
        X-Api-Key: ${NEW_RELIC_USER_KEY}

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: "local" # Alternatives - 'external'
  generator:
    runIn: "local" # Alternatives - 'local'
  publisher:
    type: "local" # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        # signIn:
        #   resolvers:
        #     - resolver: emailMatchingUserEntityProfileEmail
        # - resolver: usernameMatchingUserEntityName

#scaffolder:
# see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow:
        [
          Component,
          System,
          API,
          Resource,
          Domain,
          Location,
          User,
          Group,
          Template,
        ]
  locations:
    - type: url
      target: https://github.com/webgrip/organisation-public/blob/main/catalog/groups/c-level-group.yaml
      rules:
        - allow: [Group]
  providers:
    githubOrg:
      id: production
      githubUrl: https://github.com
      orgs: ["webgrip"]
      schedule:
        initialDelay: { seconds: 1 }
        frequency: { hours: 1 }
        timeout: { minutes: 50 }
    github:
      mainBranches:
        organization: "webgrip"
        catalogPath: "/catalog-info.yaml"
        filters:
          branch: "main"
          repository: ".*"
        schedule:
          frequency: { minutes: 35 }
          timeout: { minutes: 3 }
        validateLocationsExist: true
      masterBranches:
        organization: "webgrip"
        catalogPath: "/catalog-info.yaml"
        filters:
          branch: "master"
          repository: ".*"
        schedule:
          frequency: { minutes: 35 }
          timeout: { minutes: 3 }
        validateLocationsExist: true

sentry:
  organization: webgrip

kubernetes:
  frontend:
    podDelete:
      enabled: true
  serviceLocatorMethod:
    type: "multiTenant"
  clusterLocatorMethods:
    - type: "config"
      clusters:
        - url: ${K8S_CLUSTER}
          name: staging-doks-cluster
          title: "Staging Kubernetes Cluster"
          authProvider: "serviceAccount"
          caData: ${K8S_CONFIG_CA_DATA}
          serviceAccountToken: ${K8S_SERVICE_ACCOUNT_TOKEN_BACKSTAGE}
          dashboardUrl: http://127.0.0.1:8443
          dashboardApp: standard

# see https://backstage.io/docs/permissions/getting-started for more on the permission framework
permission:
  # setting this to `false` will disable permissions
  enabled: true

devTools:
  info:
    packagePrefixes:
      - "@backstage-community/"
      - "@dweber019/backstage-plugin-simple-icons"
      - "@opentelemetry/"
      - "@roadiehq/"
      - "@spotify/"
  externalDependencies:
    endpoints:
      - name: "Google"
        type: "fetch"
        target: "https://google.ca"
      - name: "Google Public DNS"
        type: "ping"
        target: "8.8.8.8"

search:
  pg:
    highlightOptions:
      useHighlight: true # Used to enable to disable the highlight feature. The default value is true
      maxWord: 35 # Used to set the longest headlines to output. The default value is 35.
      minWord: 15 # Used to set the shortest headlines to output. The default value is 15.
      shortWord: 3 # Words of this length or less will be dropped at the start and end of a headline, unless they are query terms. The default value of three (3) eliminates common English articles.
      highlightAll: false # If true the whole document will be used as the headline, ignoring the preceding three parameters. The default is false.
      maxFragments: 0 # Maximum number of text fragments to display. The default value of zero selects a non-fragment-based headline generation method. A value greater than zero selects fragment-based headline generation (see the linked documentation above for more details).
      fragmentDelimiter: " ... " # Delimiter string used to concatenate fragments. Defaults to " ... ".
